version: "3"
services:
  api:
    # image to build container from
    image: node:14.1.0
    # expose container port to a local port
    port:
      - "8000:3000"
    # where is the code and how to store/access it
    volumes:
      - type: bind
        source: ./server
        target: /code
    working_dir: /code
    # what to do once container has started
    command: bash -c "npm install && npm run dev"
  client:
    # image to build container from
    image: node:14.1.0
    # expose container port to a local port
    port:
      - "8080:3000"
    # where is the code and how to store/access it
    volumes:
      - type: bind
        source: ./client
        target: /code
    working_dir: /code
    # what to do once container has started
    command: bash -c "npm install && npm run dev"
  db:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=alien
        MONGO_INITDB_ROOT_PASSWORD=pword
        MONGO_INITDB_DATABASE=
    volumes:
      - dbdata:/docker-entrypoint-initdb.d/mongo-init.js:ro
